# Generated by Django 5.0.3 on 2024-05-05 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurements.measurement')),
            ],
        ),
    ]
